services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $csrfTokenName: '%contao.csrf_token_name%'
            $validExtensions: '%markocupic_member_picture_feed.valid_extensions%'
            $kernel: '@kernel'
            $contaoImageFactory: '@contao.image.factory'

    Markocupic\MemberPictureFeed\:
        resource: ../../
        exclude: ../../{Model,DependencyInjection,Resources}


    Markocupic\MemberPictureFeed\Controller\AjaxController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
