services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'

    Markocupic\MemberPictureFeed\:
        resource: ../../
        exclude: ../../{Model,DependencyInjection,Resources}


    Markocupic\MemberPictureFeed\Controller\AjaxController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
