services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $validExtensions: '%markocupic_member_picture_feed.valid_extensions%'
            $kernel: '@kernel'
            $contaoImageFactory: '@contao.image.factory'

    Markocupic\MemberPictureFeed\:
        resource: ../src/
        exclude: ../src/{Model,DependencyInjection}

    Markocupic\MemberPictureFeed\Controller\AjaxController:
        calls:
            - [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ]
